### ISSUE TITLE
Admin User/password

### ISSUE THREAD

**Issue by pixelead0** [Askedio/Laravel5-Bootstrap3-Starter-Site#1]
¿What is the admin user/password?

**Comment by gcphost** [comment]
Sorry for the (very long) delay.

The users are created by you, you can follow my article here for seeding an admin:
https://asked.io/laravel-5-2-creating-a-new-user

**Comment by gcphost** [comment]
Actually maybe it came with it, tho I didn't find it, the docs here said:

php artisan db:seed --class=UserTableSeeder
